services:
  # A web service on the Ruby native runtime
  - type: web
    runtime: python
    name: euler-formula-web
    repo: https://github.com/MrHeaven1y/heavenly_server/EulerFormulaWeb # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: frankfurt # Default: oregon
    plan: starter # Default: starter
    branch: master     # Default: master
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true # Disable automatic deploys